server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay   #Esto es el patron que vamos a implementar, el gateway va a estar enviando tokens a los recursos protegidos (en este caso user service)
      discovery:
        locator:
          enabled: true
      routes:
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/usuario/**
          filters:
            - RemoveRequestHeader=Cookie  
        - id: auto-service
          uri: lb://auto-service
          predicates:
            - Path=/auto/**
        - id: moto-service
          uri: lb://moto-service
          predicates:
            - Path=/moto/**

  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://localhost:9080/realms/basicAuth/protocol/openid-connect/auth
            userinfo-uri: http://localhost:9080/realms/basicAuth/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            token-uri: http://localhost:9080/realms/basicAuth/protocol/openid-connect/token
        registration:
          basicAuth: 
            provider: keycloak
            client-id: basicAuth 
            client-secret: P25dQP2kSegf04W1mvqRvHyfBEusgZGk
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/basicAuth"